<?php
/**
 * Sample user wide configuration file for Drush.
 */

// Activate verbose mode for all commands so they output extra information.
$options['v'] = 1;

// Directory where database dumps generated by sql-dump will be stored and format of the files.
$options['result-file'] = '/home/juampy/dbbackups/@DATABASE_@DATE.sql';

// Print warning messages. This is a nice debugging measure when you are writing a custom command.
$options['php-notices'] = 'warning';

// Generic list of tables whose data should be ignored on database dumps created by sql-dump and sql-sync.
$options['structure-tables'] = array(
  'common' => array('cache', 'cache_filter', 'cache_menu', 'cache_page', 'history', 'sessions', 'watchdog'),
);
