; This file was auto-generated by drush_make
core = 7.x

api = 2
projects[drupal][version] = "7.10"

; Modules
projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.0-rc1"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0-beta5"

projects[twitter][subdir] = "twitter"
projects[twitter][version] = "3.0-beta4"

projects[views][subdir] = "views"
projects[views][version] = "3.1"
